import React from "react";
import { Card, Row, Col, Statistic, Table, Button, Space, Tag, Input, Select, Tooltip, message } from "antd";
import {
    FileTextOutlined,
    DownloadOutlined,
    PrinterOutlined,
    SearchOutlined,
    CheckCircleOutlined,
    ClockCircleOutlined,
    BarChartOutlined,
    FileExcelOutlined,
} from "@ant-design/icons";
import styles from "./Reports.module.css";

const Reports = () => {
    const [searchText, setSearchText] = React.useState("");
    const [typeFilter, setTypeFilter] = React.useState("");
    const [statusFilter, setStatusFilter] = React.useState("");
    const [filteredData, setFilteredData] = React.useState([]);

    const reportData = [
        {
            id: 1,
            title: "Monthly Sales Report",
            date: "2024-04-01",
            type: "Sales",
            status: "completed",
            generatedBy: "Admin",
        },
        {
            id: 2,
            title: "Employee Performance",
            date: "2024-04-01",
            type: "Performance",
            status: "completed",
            generatedBy: "Manager",
        },
        {
            id: 3,
            title: "Inventory Report",
            date: "2024-04-05",
            type: "Inventory",
            status: "in-progress",
            generatedBy: "System",
        },
        {
            id: 4,
            title: "Revenue Analysis Q1",
            date: "2024-04-08",
            type: "Revenue",
            status: "completed",
            generatedBy: "Finance",
        },
        {
            id: 5,
            title: "Customer Feedback Summary",
            date: "2024-04-06",
            type: "Feedback",
            status: "completed",
            generatedBy: "Customer Service",
        },
    ];

    React.useEffect(() => {
        let filtered = reportData;

        if (searchText) {
            filtered = filtered.filter((item) => item.title.toLowerCase().includes(searchText.toLowerCase()));
        }

        if (typeFilter) {
            filtered = filtered.filter((item) => item.type === typeFilter);
        }

        if (statusFilter) {
            filtered = filtered.filter((item) => item.status === statusFilter);
        }

        setFilteredData(filtered);
    }, [searchText, typeFilter, statusFilter]);

    const totalReports = reportData.length;
    const completedReports = reportData.filter((r) => r.status === "completed").length;
    const inProgressReports = reportData.filter((r) => r.status === "in-progress").length;
    const reportTypes = [...new Set(reportData.map((r) => r.type))];

    const columns = [
        {
            title: "Report Title",
            dataIndex: "title",
            key: "title",
            width: "26%",
            sorter: (a, b) => a.title.localeCompare(b.title),
            render: (text) => <span className={styles.reportTitle}>{text}</span>,
        },
        {
            title: "Date",
            dataIndex: "date",
            key: "date",
            width: "14%",
            sorter: (a, b) => new Date(a.date) - new Date(b.date),
        },
        {
            title: "Type",
            dataIndex: "type",
            key: "type",
            width: "14%",
            render: (text) => <span className={styles.reportType}>{text}</span>,
        },
        {
            title: "Generated By",
            dataIndex: "generatedBy",
            key: "generatedBy",
            width: "16%",
        },
        {
            title: "Status",
            dataIndex: "status",
            key: "status",
            width: "14%",
            render: (status) => (
                <Tag
                    icon={status === "completed" ? <CheckCircleOutlined /> : <ClockCircleOutlined />}
                    className={status === "completed" ? styles.statusCompleted : styles.statusInProgress}
                >
                    {status === "completed" ? "Hoàn thành" : "Đang xử lý"}
                </Tag>
            ),
        },
        {
            title: "Actions",
            key: "actions",
            width: "16%",
            render: (_, record) => (
                <div className={styles.actionButtons}>
                    <Tooltip title="Tải xuống">
                        <Button
                            icon={<DownloadOutlined />}
                            size="small"
                            onClick={() => message.success(`Tải xuống ${record.title}`)}
                        />
                    </Tooltip>
                    <Tooltip title="In ấn">
                        <Button
                            icon={<PrinterOutlined />}
                            size="small"
                            onClick={() => message.success(`In ${record.title}`)}
                        />
                    </Tooltip>
                </div>
            ),
        },
    ];

    return (
        <div className={styles.reportsPage}>
            <div className={styles.header}>
                <h1 className={styles.headerTitle}>📋 Báo cáo & Phân tích</h1>
                <Button type="primary" icon={<FileExcelOutlined />} size="large" style={{ borderRadius: "6px" }}>
                    Export All
                </Button>
            </div>

            <Row gutter={[16, 16]} className={styles.statsGrid}>
                <Col xs={12} sm={12} md={6}>
                    <Card className={styles.statCard}>
                        <Statistic
                            title="Tổng báo cáo"
                            value={totalReports}
                            prefix={<FileTextOutlined style={{ color: "#667eea" }} />}
                        />
                    </Card>
                </Col>
                <Col xs={12} sm={12} md={6}>
                    <Card className={styles.statCard}>
                        <Statistic
                            title="Đã hoàn thành"
                            value={completedReports}
                            prefix={<CheckCircleOutlined style={{ color: "#52c41a" }} />}
                            valueStyle={{ color: "#52c41a" }}
                        />
                    </Card>
                </Col>
                <Col xs={12} sm={12} md={6}>
                    <Card className={styles.statCard}>
                        <Statistic
                            title="Đang xử lý"
                            value={inProgressReports}
                            prefix={<ClockCircleOutlined style={{ color: "#faad14" }} />}
                            valueStyle={{ color: "#faad14" }}
                        />
                    </Card>
                </Col>
                <Col xs={12} sm={12} md={6}>
                    <Card className={styles.statCard}>
                        <Statistic
                            title="Loại báo cáo"
                            value={reportTypes.length}
                            prefix={<BarChartOutlined style={{ color: "#1890ff" }} />}
                            valueStyle={{ color: "#1890ff" }}
                        />
                    </Card>
                </Col>
            </Row>

            <Card className={styles.tableCard} title="📊 Danh sách báo cáo gần đây">
                <div className={styles.toolbar}>
                    <Input
                        placeholder="Tìm kiếm báo cáo..."
                        prefix={<SearchOutlined />}
                        value={searchText}
                        onChange={(e) => setSearchText(e.target.value)}
                        className={styles.searchInput}
                        allowClear
                        size="large"
                    />
                    <Select
                        placeholder="Tất cả loại"
                        style={{ width: "160px" }}
                        value={typeFilter || undefined}
                        onChange={(value) => setTypeFilter(value)}
                        allowClear
                        size="large"
                        options={reportTypes.map((type) => ({ label: type, value: type }))}
                    />
                    <Select
                        placeholder="Tất cả trạng thái"
                        style={{ width: "160px" }}
                        value={statusFilter || undefined}
                        onChange={(value) => setStatusFilter(value)}
                        allowClear
                        size="large"
                        options={[
                            { label: "Hoàn thành", value: "completed" },
                            { label: "Đang xử lý", value: "in-progress" },
                        ]}
                    />
                </div>

                <Table
                    columns={columns}
                    dataSource={filteredData.map((item) => ({ ...item, key: item.id }))}
                    pagination={{ pageSize: 10, showSizeChanger: true, showTotal: (total) => `Tổng ${total} báo cáo` }}
                    className={styles.table}
                    locale={{
                        emptyText: (
                            <div style={{ textAlign: "center", padding: "40px", color: "#999" }}>
                                Không có báo cáo{searchText && ` cho "${searchText}"`}
                            </div>
                        ),
                    }}
                />
            </Card>
        </div>
    );
};

export default Reports;
